---
# This is the master controller for the dev kit series of scripts.
- name: Master Control
  hosts: devbox
  force_handlers: true
  become: yes
  become_user: "{{ user }}"
  vars_files:
    - ./vars.yml
  roles:
    - base
