---
# This is the master controller for the dev kit series of scripts.
- name: Master Control
  hosts: mlbot
  force_handlers: true
  become: yes
  become_user: "{{ user }}"
  vars_files:
    - ./vars.yml
  roles:
    - configure_system
    - basic_tooling
    - configuration_files
    # - comfyui
