---
- name: Install AliceVision
  hosts: all
  become: yes
  become_user: "{{ user }}"
  vars_files:
    - ./vars.yml
  tasks:
    - name: Ensure Cmake
      apt:
        pkg:
          - cmake
          - gcc
          - python3

    - name: Ensure Git
      apt:
        pkg:
          - git

    - name: Ensure clang / gcc / llvm
      ansible.builtin.git:
        repo: "https://github.com/llvm/llvm-project.git"
        dest: "/home/{{ user }}/tools/llvm"
