---
- name: Pull Configs
  block:
    - name: Ensure .config exists
      file:
        state: directory
        path: "/home/{{ user }}/.config"
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: 0755
    
    - name: Pull configs from github
      git:
        repo: "{{ repo }}/configurations"
        dest: "/home/{{ user }}/.config/configurations"
        accept_hostkey: yes
        key_file: "/home/{{ user }}/.ssh/id_rsa"
      become: yes
      become_user: "{{ user }}"


    - name: Symlink .emacs
      file:
        state: link
        src: "/home/{{ user }}/.config/configurations/.emacs"
        dest: "/home/{{ user }}/.emacs"
        owner: "{{ user }}"
        force: yes

    - name: Symlink .zshrc
      file:
        state: link
        src: "/home/{{ user }}/.config/configurations/.zshrc"
        dest: "/home/{{ user }}/.zshrc"
        owner: "{{ user }}"
        force: yes

    - name: Set up cron for configs on reboot
      cron:
        name: "push config"
        job: "/home/{{ user }}/.config/configurations/cronpush.sh"
        special_time: reboot
        user: "{{ user }}"

    - name: Set up cron for configs nightly
      cron:
        name: "push config"
        job: "/home/{{ user }}/.config/configurations/cronpush.sh"
        hour: "3"
        minute: "0"
        user: "{{ user }}"
