---
# This playbook *should* download and build emacs28 from source
# set up to leverage new libjansson features for native compilation
# in order to speed up LSP.  It is designed for Ubuntu 20.04 focal fossa,
# but may work on other platforms.

# There are three places, marked below, where you must set the username

# if using this to provision locally, make sure to set
# 
# hosts: localhost

# instructions provided by
# https://www.masteringemacs.org/article/speed-up-emacs-libjansson-native-elisp-compilation

- name: Install latest emacs
  hosts: all
  become: <username> # Set to username 
  user: <username> # Set to username
  vars:
    proxy_env:
      CC: "gcc-10"
    homedir: /home/<username> # Set to user's home directory
  tasks:

    - name: Add apt repo for gcc10
      apt_repository:
        repo: ppa:ubuntu-toolchain-r/ppa

    - name: Update apt
      apt:
        upgrade: full
      become: yes
        
    - name: Install libtiff-dev first for some reason
      apt:
        name: 'libtiff-dev'
        state: present
        
    - name: Install emacs dependancies
      apt:
        pkg:
          - libgtk-3-dev
          - libgif-dev
          - libjpeg-dev
          - libpng-dev
          - libxpm-dev
          - libncurses-dev
          - build-essential
          - libjansson4
          - libjansson-dev
          - git
          - autoconf
          - libgccjit0
          - libgccjit-9-dev     # this is here due to a bug in v10
          - libjansson4
          - libjansson-dev
          - texinfo
          - libgnutls28-dev
          - fonts-firacode
          - fonts-powerline
          - gcc-10
      state: present
      become: yes

    - name: Grab emacs from github
      git:
        repo: https://git.savannah.gnu.org/git/emacs.git
        dest: "{{ homedir }}/.sources/emacs"
        version: origin/feature/native-comp

    - name: set permissions for autogen
      command: "chmod +x {{ homedir }}/.sources/emacs/autogen.sh"

    - name: Run autogen
      command: "sh autogen.sh"
      args:
        chdir: '{{ homedir }}/.sources/emacs/'
      
    - name: set permissions for configure
      command: "chmod +x {{ homedir }}/.sources/emacs/configure"
 
    - name: Run configure
      command: "sh ./configure --with-nativecomp --with-mailutils --with-cairo --with-x-toolkit=gtk3 --without-makeinfo"
      args:
        chdir: '{{ homedir }}/.sources/emacs/'

    - name: Set C compiler to gcc-10 to avoid smoke test problems 
      shell: export CC="gcc-10"

    - name: Make Build
      make:
        chdir: "{{ homedir }}/.sources/emacs"
      environment:
        CC: "gcc-10"
        CXX: "gcc-10" 

    # In vagrant, this claims to fail but everything is OK. 
    - name: Make install
      make:
        chdir: "{{ homedir }}/.source/emacs"
        target: "install"
      become: yes
      become_method: sudo
