---
- name: Install fonts
  block:
    - name: Ensure fonts .sources file exists
      file:
        state: directory
        mode: 0755
        owner: "{{ user }}"
        path: "/home/{{ user }}/.sources/fonts"

    - name: Ensure fonts file exists
      file:
        state: directory
        mode: 0755
        owner: "{{ user }}"
        path: "/home/{{ user }}/.local/share/fonts"

    - name: SSH forward for fonts
      include_role:
        name: ssh_forward

    - name: DM-Mono  grab from git
      become_user: "{{ user }}"
      git:
        repo: "git@github.com:googlefonts/dm-mono"
        dest: "/home/{{ user }}/.sources/fonts/dm-mono"
        accept_hostkey: yes

    - name: DM-Mono  Install fonts -> loop
      copy:
        remote_src: yes
        src: "/home/{{ user }}/.sources/fonts/dm-mono/exports/{{ item }}"
        dest: "/home/{{ user }}/.local/share/fonts/{{ item }}"
        owner: "{{ user }}"
      loop:
        - DMMono-Light.ttf
        - DMMono-Regular.ttf
        - DMMono-Medium.ttf
