---
- name: Pull Configs
  block:
    - name: Ensure .config exists
      file:
        state: directory
        path: "/home/{{ user }}/.config"
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: 0755

    - name: Pull configs from github
      become: yes
      become_user: "{{ user }}"
      git:
        repo: "{{ user_github_account }}/configurations"
        dest: "/home/{{ user }}/.config/configurations"
        accept_hostkey: yes
        force: true

    - name: Symlink .emacs
      file:
        state: link
        src: "/home/{{ user }}/.config/configurations/{{ ansible_distribution }}/emacs"
        dest: "/home/{{ user }}/.emacs"
        owner: "{{ user }}"
        force: yes

    - name: Symlink .zshrc
      file:
        state: link
        src: "/home/{{ user }}/.config/configurations/{{ ansible_distribution }}/zshrc"
        dest: "/home/{{ user }}/.zshrc"
        owner: "{{ user }}"
        force: yes
